version: "3"

services:
  # test:
  #   image: nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
  #   command: nvidia-smi
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [gpu]
  fooocus-mre:
    build:
      context: .
      dockerfile: docker/Dockerfile.Fooocus-MRE
    user: vscode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # 该参数必须出现
              count: all
              capabilities: [gpu]
    working_dir: /workspace/Fooocus-MRE
    volumes:
      - /mnt:/mnt
      - ~/.cache:/home/vscode/.cache
      - ~/.vscode-server:/home/vscode/.vscode-server
      - ~/.vscode-server-insiders:/home/vscode/.vscode-server-insiders
      - ~/.codeium/:/home/vscode/.codeium
      # ====================================================================
      - ./Fooocus-MRE:/workspace/Fooocus-MRE
      - ./mount/repositories/:/workspace/Fooocus-MRE/repositories:ro
      - ./mount/fooocus-mre-launch.py:/workspace/Fooocus-MRE/launch.py:ro
      - ./mount/storage/models:/workspace/Fooocus-MRE/models:ro
      - ./mount/storage/outputs:/workspace/Fooocus-MRE/outputs:rw
    ports:
      - 7860:7860
    command: python launch.py

  comfy-ui:
    build:
      context: .
      dockerfile: docker/Dockerfile.ComfyUI
    user: vscode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # 该参数必须出现
              count: all
              capabilities: [gpu]
    working_dir: /workspace/ComfyUI
    volumes:
      - /mnt:/mnt
      - ~/.cache:/home/vscode/.cache
      - ~/.vscode-server:/home/vscode/.vscode-server
      - ~/.vscode-server-insiders:/home/vscode/.vscode-server-insiders
      - ~/.codeium/:/home/vscode/.codeium
      # ====================================================================
      - ./ComfyUI:/workspace/ComfyUI
      - ./mount/custom_nodes:/workspace/ComfyUI/custom_nodes:rw
      - ./mount/storage/models:/workspace/ComfyUI/models:rw
      - ./mount/storage/outputs/ComfyUI:/workspace/ComfyUI/output:rw
      - ./mount/storage/custom_nodes/ComfyUI_IPAdapter_plus/models:/workspace/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/models:ro
    ports:
      - 8188:8188
    command: python main.py --listen=0.0.0.0
