version: "3"

services:
  gpu-test:
    image: nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  fooocus:
    build:
      context: .
      dockerfile: docker/Dockerfile.Fooocus
    user: vscode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # 该参数必须出现
              count: all
              capabilities: [gpu]
    working_dir: /app
    volumes:
      - /mnt:/mnt
      - ~/.cache:/home/vscode/.cache
      - ~/.vscode-server:/home/vscode/.vscode-server
      - ~/.vscode-server-insiders:/home/vscode/.vscode-server-insiders
      - ~/.codeium/:/home/vscode/.codeium
      # ====================================================================
      - ./Fooocus:/app
      - ./mount/Fooocus/repositories/:/app/repositories:ro
      - ./mount/Fooocus/launch.py:/app/launch.py:ro
      - ./mount/storage/models:/app/models:rw
      - ./mount/storage/outputs:/app/outputs:rw
    ports:
      - 8188:8188
    command: python launch.py --listen=0.0.0.0
  fooocus-mre:
    build:
      context: .
      dockerfile: docker/Dockerfile.Fooocus
    user: vscode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # 该参数必须出现
              count: all
              capabilities: [gpu]
    working_dir: /app
    volumes:
      - /mnt:/mnt
      - ~/.cache:/home/vscode/.cache
      - ~/.vscode-server:/home/vscode/.vscode-server
      - ~/.vscode-server-insiders:/home/vscode/.vscode-server-insiders
      - ~/.codeium/:/home/vscode/.codeium
      # ====================================================================
      - ./Fooocus-MRE:/app
      - ./mount/Fooocus-MRE/repositories/:/app/repositories:ro
      - ./mount/Fooocus-MRE/launch.py:/app/launch.py:ro
      - ./mount/storage/models:/app/models:ro
      - ./mount/storage/outputs:/app/outputs:rw
    ports:
      - 7860:7860
    command: python launch.py --listen=0.0.0.0

  comfy-ui:
    build:
      context: .
      dockerfile: docker/Dockerfile.ComfyUI
    user: vscode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # 该参数必须出现
              count: all
              capabilities: [gpu]
    working_dir: /app
    volumes:
      - /mnt:/mnt
      - ~/.cache:/home/vscode/.cache
      - ~/.vscode-server:/home/vscode/.vscode-server
      - ~/.vscode-server-insiders:/home/vscode/.vscode-server-insiders
      - ~/.codeium/:/home/vscode/.codeium
      # ====================================================================
      - ./ComfyUI:/app
      - ./mount/ComfyUI/custom_nodes:/app/custom_nodes:rw
      - ./mount/ComfyUI/temp:/app/temp:rw
      - ./mount/storage/models:/app/models:rw
      - ./mount/storage/outputs/ComfyUI:/app/output:rw
      - ./mount/storage/custom_nodes/ComfyUI_IPAdapter_plus/models:/app/custom_nodes/ComfyUI_IPAdapter_plus/models:ro
    ports:
      - 8188:8188
    command: python main.py --listen=0.0.0.0
