version: "3"

services:
  gpu-test:
    image: nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  fooocus:
    build:
      context: .
      dockerfile: docker/Dockerfile.Fooocus
    user: vscode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # 该参数必须出现
              count: all
              capabilities: [gpu]
    working_dir: /app
    volumes:
      - /mnt:/mnt
      - ~/.config:/home/vscode/.config
      - ~/.cache:/home/vscode/.cache
      - ~/.vscode-server:/home/vscode/.vscode-server
      - ~/.vscode-server-insiders:/home/vscode/.vscode-server-insiders
      - ~/.codeium/:/home/vscode/.codeium
      # ====================================================================
      - ./Fooocus:/app
      - ./mount/storage/models/:/app/models/
      - ./Fooocus/models/configs:/app/models/configs
      - ./Fooocus/models/prompt_expansion:/app/models/prompt_expansion
      - ./mount/storage/outputs:/app/outputs:rw

    ports:
      - 7860:7860
    command: python3 launch.py --listen=0.0.0.0
  comfy-ui:
    build:
      context: .
      dockerfile: docker/Dockerfile.ComfyUI
    user: vscode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # 该参数必须出现
              count: all
              capabilities: [gpu]
    working_dir: /app
    volumes:
      - /mnt:/mnt
      - ~/.config:/home/vscode/.config
      - ~/.cache:/home/vscode/.cache
      - ~/.vscode-server:/home/vscode/.vscode-server
      - ~/.vscode-server-insiders:/home/vscode/.vscode-server-insiders
      - ~/.codeium/:/home/vscode/.codeium
      # ====================================================================
      - ./ComfyUI:/app:rw
      - ./mount/ComfyUI/custom_nodes:/app/custom_nodes:rw
      - ./mount/ComfyUI/temp:/app/temp:rw
      - ./mount/storage/models:/app/models:rw
      - ./mount/storage/custom_nodes/ComfyUI_IPAdapter_plus/models:/app/custom_nodes/ComfyUI_IPAdapter_plus/models
      - ./mount/storage/outputs/ComfyUI:/app/output:rw
    ports:
      - 8188:8188
    command: python3 main.py --listen=0.0.0.0
