FROM huodon/pytorch-devcontainer:121

USER vscode

ENV PATH=:/home/vscode/.local/bin:$PATH
WORKDIR /app

COPY ./docker/install-shared.sh .
COPY ./docker/install-comfyui.sh .

RUN bash ./install-shared.sh
RUN bash ./install-comfyui.sh

# ComfyUI
RUN pip install --user --no-cache-dir -r \
  https://raw.githubusercontent.com/comfyanonymous/ComfyUI/master/requirements.txt

