FROM huodon/cuda-devel:12.1.1

USER vscode

ENV PATH=:/home/vscode/.local/bin:$PATH
WORKDIR /app

COPY ./docker/install-shared.sh .
COPY ./docker/install-comfyui.sh .
COPY --chown=vscode ./docker/build ./build


RUN bash ./install-shared.sh
RUN bash ./install-comfyui.sh
RUN rm -rf ./build

# ComfyUI
RUN pip install --user --no-cache-dir -r \
  https://raw.githubusercontent.com/comfyanonymous/ComfyUI/master/requirements.txt