FROM huodon/pytorch-devcontainer:118

USER vscode

ENV PATH=:/home/vscode/.local/bin:$PATH

WORKDIR /app

COPY ./docker/install.sh .

RUN bash ./install.sh

RUN pip install --no-cache-dir -r \
  https://raw.githubusercontent.com/lllyasviel/Fooocus/main/requirements_versions.txt