FROM huodon/pytorch-devcontainer:121

USER vscode

ENV PATH=/home/vscode/.local/bin:$PATH

WORKDIR /app

COPY ./docker/install-shared.sh .

RUN bash ./install-shared.sh

RUN pip install --user --no-cache-dir -r \
  https://raw.githubusercontent.com/lllyasviel/Fooocus/main/requirements_versions.txt